CREATE TABLE IF NOT EXISTS lists (
  id SERIAL NOT NULL PRIMARY KEY,
  key VARCHAR (50) UNIQUE NOT NULL,
  page_count INTEGER NOT NULL DEFAULT 0,
  next_page_key VARCHAR (50) REFERENCES pages(key),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER set_timestamp_lists
BEFORE UPDATE ON lists
FOR EACH ROW
EXECUTE PROCEDURE trigger_set_timestamp();


