-- CREATE TABLE IF NOT EXISTS users(
  -- user_id SERIAL NOT NULL PRIMARY KEY,
  -- username VARCHAR (50) UNIQUE NOT NULL,
  -- password VARCHAR (50) NOT NULL,
  -- created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  -- updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
-- );

CREATE TABLE IF NOT EXISTS users (
  id SERIAL NOT NULL PRIMARY KEY,
  username VARCHAR (50) UNIQUE NOT NULL,
  -- password VARCHAR (50) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER set_timestamp_users
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE PROCEDURE trigger_set_timestamp();
