CREATE TABLE IF NOT EXISTS pages (
  id SERIAL NOT NULL PRIMARY KEY,
  key VARCHAR (50) UNIQUE NOT NULL,
  next_id INTEGER REFERENCES pages(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER set_timestamp_pages
BEFORE UPDATE ON pages
FOR EACH ROW
EXECUTE PROCEDURE trigger_set_timestamp();


