CREATE TABLE IF NOT EXISTS topics (
  id SERIAL NOT NULL PRIMARY KEY,
  name VARCHAR (50) UNIQUE NOT NULL,
  description VARCHAR (250),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER set_timestamp_topics
BEFORE UPDATE ON topics
FOR EACH ROW
EXECUTE PROCEDURE trigger_set_timestamp();

