// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package pgcodegen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Article struct {
	ID        int32
	Title     string
	Content   string
	AuthorID  pgtype.Int4
	TopicID   pgtype.Int4
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type List struct {
	ID            int32
	Key           string
	NextPageKey   pgtype.Text
	LatestPageKey pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type Page struct {
	ID          int32
	Key         string
	NextPageKey pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	ListKey     string
}

type Topic struct {
	ID          int32
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type User struct {
	ID        int32
	Username  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
