// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: query.sql

package pgcodegen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createList = `-- name: CreateList :one
INSERT INTO lists (key, next_page_key, latest_page_key) VALUES ($1, $2, $3) RETURNING id, key, next_page_key, latest_page_key, created_at, updated_at
`

type CreateListParams struct {
	Key           string
	NextPageKey   pgtype.Text
	LatestPageKey pgtype.Text
}

func (q *Queries) CreateList(ctx context.Context, arg CreateListParams) (List, error) {
	row := q.db.QueryRow(ctx, createList, arg.Key, arg.NextPageKey, arg.LatestPageKey)
	var i List
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.NextPageKey,
		&i.LatestPageKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPage = `-- name: CreatePage :one
INSERT INTO pages (key, next_page_key, list_key) VALUES ($1, $2, $3)
RETURNING id, key, next_page_key, created_at, updated_at, list_key
`

type CreatePageParams struct {
	Key         string
	NextPageKey pgtype.Text
	ListKey     string
}

func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) (Page, error) {
	row := q.db.QueryRow(ctx, createPage, arg.Key, arg.NextPageKey, arg.ListKey)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.NextPageKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ListKey,
	)
	return i, err
}

const deleteListByKey = `-- name: DeleteListByKey :execrows
DELETE FROM lists
WHERE key = $1
`

func (q *Queries) DeleteListByKey(ctx context.Context, key string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteListByKey, key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePageByKey = `-- name: DeletePageByKey :execrows
DELETE FROM pages
WHERE key = $1
`

func (q *Queries) DeletePageByKey(ctx context.Context, key string) (int64, error) {
	result, err := q.db.Exec(ctx, deletePageByKey, key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getArticleByID = `-- name: GetArticleByID :one
SELECT id, title, content, author_id, topic_id, created_at, updated_at FROM articles
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetArticleByID(ctx context.Context, id int32) (Article, error) {
	row := q.db.QueryRow(ctx, getArticleByID, id)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.AuthorID,
		&i.TopicID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getListByID = `-- name: GetListByID :one
SELECT id, key, next_page_key, latest_page_key, created_at, updated_at FROM lists
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetListByID(ctx context.Context, id int32) (List, error) {
	row := q.db.QueryRow(ctx, getListByID, id)
	var i List
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.NextPageKey,
		&i.LatestPageKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getListByKey = `-- name: GetListByKey :one
SELECT id, key, next_page_key, latest_page_key, created_at, updated_at FROM lists
WHERE key = $1 LIMIT 1
`

func (q *Queries) GetListByKey(ctx context.Context, key string) (List, error) {
	row := q.db.QueryRow(ctx, getListByKey, key)
	var i List
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.NextPageKey,
		&i.LatestPageKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPageByID = `-- name: GetPageByID :one
SELECT id, key, next_page_key, created_at, updated_at, list_key FROM pages
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPageByID(ctx context.Context, id int32) (Page, error) {
	row := q.db.QueryRow(ctx, getPageByID, id)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.NextPageKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ListKey,
	)
	return i, err
}

const getPageByKey = `-- name: GetPageByKey :one
SELECT id, key, next_page_key, created_at, updated_at, list_key FROM pages
WHERE key = $1 LIMIT 1
`

func (q *Queries) GetPageByKey(ctx context.Context, key string) (Page, error) {
	row := q.db.QueryRow(ctx, getPageByKey, key)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.NextPageKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ListKey,
	)
	return i, err
}

const getTopicByID = `-- name: GetTopicByID :one
SELECT id, name, description, created_at, updated_at FROM topics
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTopicByID(ctx context.Context, id int32) (Topic, error) {
	row := q.db.QueryRow(ctx, getTopicByID, id)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, created_at, updated_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listArticles = `-- name: ListArticles :many
SELECT id, title, content, author_id, topic_id, created_at, updated_at FROM articles
ORDER BY created_at
`

func (q *Queries) ListArticles(ctx context.Context) ([]Article, error) {
	rows, err := q.db.Query(ctx, listArticles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.AuthorID,
			&i.TopicID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLists = `-- name: ListLists :many
SELECT id, key, next_page_key, latest_page_key, created_at, updated_at FROM lists
ORDER BY created_at
`

func (q *Queries) ListLists(ctx context.Context) ([]List, error) {
	rows, err := q.db.Query(ctx, listLists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []List
	for rows.Next() {
		var i List
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.NextPageKey,
			&i.LatestPageKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPages = `-- name: ListPages :many
SELECT id, key, next_page_key, created_at, updated_at, list_key FROM pages
ORDER BY created_at
`

func (q *Queries) ListPages(ctx context.Context) ([]Page, error) {
	rows, err := q.db.Query(ctx, listPages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Page
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.NextPageKey,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ListKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopics = `-- name: ListTopics :many
SELECT id, name, description, created_at, updated_at FROM topics
ORDER BY created_at
`

func (q *Queries) ListTopics(ctx context.Context) ([]Topic, error) {
	rows, err := q.db.Query(ctx, listTopics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Topic
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, created_at, updated_at FROM users
ORDER BY created_at
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateListByKey = `-- name: UpdateListByKey :one
UPDATE lists
SET
  next_page_key = $1,
  latest_page_key = $2
WHERE key = $3
RETURNING id, key, next_page_key, latest_page_key, created_at, updated_at
`

type UpdateListByKeyParams struct {
	NextPageKey   pgtype.Text
	LatestPageKey pgtype.Text
	Key           string
}

func (q *Queries) UpdateListByKey(ctx context.Context, arg UpdateListByKeyParams) (List, error) {
	row := q.db.QueryRow(ctx, updateListByKey, arg.NextPageKey, arg.LatestPageKey, arg.Key)
	var i List
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.NextPageKey,
		&i.LatestPageKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePageByKey = `-- name: UpdatePageByKey :one
UPDATE pages
SET
  next_page_key = $1
WHERE key = $2
RETURNING id, key, next_page_key, created_at, updated_at, list_key
`

type UpdatePageByKeyParams struct {
	NextPageKey pgtype.Text
	Key         string
}

func (q *Queries) UpdatePageByKey(ctx context.Context, arg UpdatePageByKeyParams) (Page, error) {
	row := q.db.QueryRow(ctx, updatePageByKey, arg.NextPageKey, arg.Key)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.NextPageKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ListKey,
	)
	return i, err
}
