basePath: /v1
info:
  contact: {}
  title: Shared Key Value List System API
  version: "1.0"
paths:
  /page:
    get:
      consumes:
      - application/json
      description: test
      produces:
      - application/json
      responses:
        "200":
          description: Hello World!
          schema:
            type: string
      summary: Page API
swagger: "2.0"
